package dev.draftwatch.app;

import dev.draftwatch.config.DraftwatchConfig;
import dev.draftwatch.config.SbatchOptions;
import dev.draftwatch.config.SlurmConfig;
import dev.draftwatch.exec.slurm.ShellQuote;
import dev.draftwatch.exec.slurm.SlurmCli;
import dev.draftwatch.fingerprint.Sha256;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.TreeSet;

/**
 * The self-resubmitting watch job of one state directory (DECISIONS.md D63): the files under
 * {@code <state>/schedule/}, the job's sbatch options, and the generated script. The script
 * checks its token, resubmits itself, and only then runs {@code watch --once}, so a crash in
 * {@code watch} never stops the schedule.
 */
final class Schedule {
  static final String DIR = "schedule";
  static final Duration DEFAULT_INTERVAL = Duration.ofMinutes(15);
  static final Duration MIN_INTERVAL = Duration.ofSeconds(60);

  private final Path dir;
  private final Path configFile;
  private final Path workingDir;
  private final String jobName;
  private final List<String> extraArgs;
  private final List<String> launcher;

  private Schedule(
      Path dir,
      Path configFile,
      Path workingDir,
      String jobName,
      List<String> extraArgs,
      List<String> launcher) {
    this.dir = dir;
    this.configFile = configFile;
    this.workingDir = workingDir;
    this.jobName = jobName;
    this.extraArgs = extraArgs;
    this.launcher = launcher;
  }

  /**
   * The schedule of {@code config}'s state directory.
   *
   * @param launcher the command that starts draftwatch, such as {@code java -cp ... Main}
   */
  static Schedule of(DraftwatchConfig config, List<String> launcher) {
    Path state = config.stateDir().toAbsolutePath();
    String hash = Sha256.hex(state.toString().getBytes(StandardCharsets.UTF_8)).substring(0, 8);
    List<String> extra =
        config
            .executor()
            .slurm()
            .map(SlurmConfig::scheduleSbatchArgs)
            .orElse(SlurmConfig.DEFAULT_SCHEDULE_SBATCH_ARGS);
    return new Schedule(
        state.resolve(DIR),
        config.configFile().toAbsolutePath(),
        config.baseDir().toAbsolutePath(),
        "draftwatch-watch-" + hash,
        extra,
        List.copyOf(launcher));
  }

  Path dir() {
    return dir;
  }

  Path script() {
    return dir.resolve("watch.sbatch");
  }

  /** Holds the current schedule's token; removing it ends the schedule. */
  Path active() {
    return dir.resolve("active");
  }

  /** The id of the latest scheduled job. */
  Path jobIdFile() {
    return dir.resolve("job_id");
  }

  /** Written when a resubmission fails. */
  Path stopped() {
    return dir.resolve("stopped");
  }

  Path log() {
    return dir.resolve("watch.log");
  }

  /** {@code draftwatch-watch-<first 8 hex of the state directory's SHA-256>}. */
  String jobName() {
    return jobName;
  }

  /** The job's sbatch options, without {@code --begin}; none requests a GPU. */
  List<String> options() {
    List<String> options = new ArrayList<>();
    options.add("--job-name=" + jobName);
    options.add("--output=" + log());
    options.add("--error=" + log());
    options.add("--open-mode=append");
    options.add("--chdir=" + workingDir);
    options.add("--no-requeue"); // a rerun after a node failure would start a second chain
    options.addAll(extraArgs);
    return options;
  }

  /** The options of a resubmission: {@link #options()} and {@code --begin=now+<seconds>}. */
  List<String> resubmitOptions(Duration interval) {
    List<String> options = options();
    options.add("--begin=now+" + interval.getSeconds());
    return options;
  }

  /** The command the script ends with. */
  List<String> watchCommand() {
    List<String> command = new ArrayList<>(launcher);
    command.addAll(List.of("watch", "--once", "--config", configFile.toString()));
    return command;
  }

  /** The script, a POSIX {@code sh} file with every value embedded and quoted. */
  String script(String token, Duration interval, Instant generatedAt) {
    String d = ShellQuote.quote(dir.toString());
    List<String> resubmit =
        SlurmCli.sbatchArgv(resubmitOptions(interval), script(), List.of());
    return "#!/bin/sh\n"
        + "# Generated by 'draftwatch schedule' at " + generatedAt + "; do not edit, run it"
        + " again instead.\n"
        + "# Each run resubmits itself, then runs one watch pass, so a failing pass never stops"
        + " the\n"
        + "# schedule. 'draftwatch unschedule' ends it (DECISIONS.md D63).\n"
        + "dir=" + d + "\n"
        + "token=" + ShellQuote.quote(token) + "\n"
        + "echo \"=== Slurm job ${SLURM_JOB_ID:-?} on $(hostname) at"
        + " $(date -u +%Y-%m-%dT%H:%M:%SZ)\"\n"
        + "if [ \"$(cat \"$dir/active\" 2>/dev/null)\" != \"$token\" ]; then\n"
        + "  echo \"draftwatch schedule: $dir/active does not hold this schedule's token;"
        + " not resubmitting\"\n"
        + "  exit 0\n"
        + "fi\n"
        + "unset " + String.join(" ", new TreeSet<>(SbatchOptions.GPU_VARIABLES)) + "\n"
        + "if next=$(" + ShellQuote.join(resubmit) + "); then\n"
        + "  printf '%s\\n' \"$next\" > \"$dir/job_id.tmp\" && mv \"$dir/job_id.tmp\""
        + " \"$dir/job_id\"\n"
        + "  echo \"draftwatch schedule: next pass is Slurm job $next\"\n"
        + "else\n"
        + "  echo \"draftwatch schedule: resubmission failed; the schedule has stopped\" >&2\n"
        + "  date -u +%Y-%m-%dT%H:%M:%SZ > \"$dir/stopped\"\n"
        + "fi\n"
        + "exec " + ShellQuote.join(watchCommand()) + "\n";
  }

  /** The token in {@link #active()}, if the file exists. */
  Optional<String> token() throws IOException {
    return read(active());
  }

  Optional<String> jobId() throws IOException {
    return read(jobIdFile());
  }

  Optional<String> stoppedAt() throws IOException {
    return read(stopped());
  }

  private static Optional<String> read(Path file) throws IOException {
    try {
      return Optional.of(Files.readString(file, StandardCharsets.UTF_8).trim());
    } catch (NoSuchFileException e) {
      return Optional.empty();
    }
  }

  @Override
  public String toString() {
    return "Schedule{" + jobName + " in " + dir + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Schedule)) {
      return false;
    }
    Schedule that = (Schedule) o;
    return dir.equals(that.dir)
        && configFile.equals(that.configFile)
        && workingDir.equals(that.workingDir)
        && jobName.equals(that.jobName)
        && extraArgs.equals(that.extraArgs)
        && launcher.equals(that.launcher);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dir, configFile, workingDir, jobName, extraArgs, launcher);
  }
}
